mammals_clean
mammals_genus

mammals_c <- read.csv('C:/Users/daire/Desktop/mammals_clean.csv')
mammals_g <- read.csv('C:/Users/daire/Desktop/UGH/mammals_genus.csv')
mammals_o <- read.csv('C:/Users/daire/Desktop/UGH/mammals_order.csv')


mammals<- Mammal_lifehistories_v2

library(tidyverse)

##### Simulation Test #####
mammals2 <- mammals_clean %>%
  group_by(order) %>% 
  summarize(order_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))

mammals3 <- mammals_clean %>%
  group_by(Genus) %>% 
  summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))

result <- lm(genus_size~litter_size, data=mammals3)
summary(result)



write.csv(mammals2, "mammals_order.csv")
write.csv(mammals3, "mammals_genus.csv")

result <- lm(genus_size~litter_size, data=mammals_g)
summary(result)

#randomization test
set.seed
reshuffled <- mammals_c
reshuffled$litter_size <- sample(reshuffled$litter_size, size = nrow(reshuffled), replace = FALSE)
slope_real <- coef(result)["litter_size"]
simulated_slopes <- list()
nreps = 50# 5000 iterations
for(i in 1:nreps){
  
  reshuffled <- mammals_c
  reshuffled$litter_size <- sample(reshuffled$litter_size, size = nrow(reshuffled),
                                    replace = FALSE)
  
  # Calculate the slope
  genus_temp <- reshuffled %>%
    group_by(Genus) %>% 
    summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
              gestation_mo = mean(gestation_mo, na.rm = TRUE),
              newborn_g = mean(newborn_g, na.rm = TRUE),
              weaning_mo = mean(weaning_mo, na.rm = TRUE),
              wean_g = mean(wean_g, na.rm = TRUE),
              afr_mo = mean(afr_mo, na.rm = TRUE),
              life_mo = mean(life_mo, na.rm = TRUE),
              litter_size = mean(litter_size, na.rm = TRUE),
              litters_per_year = mean(litters_per_year, na.rm = TRUE))
  
  reshuffled_res <- lm(genus_size~litter_size, data=genus_temp)
  slope_sim <- coef(reshuffled_res)["litter_size"]
  
  # Append simulated slope to list
  simulated_slopes[i] <- slope_sim
}    

# Unlist simulated means list into numeric vector
simulated_slopes <- unlist(simulated_slopes)
ggplot() +
  ylab("Count") + xlab("Simulated slope") +
  geom_histogram(aes(x = simulated_slopes), bins = 30, 
                 fill = "grey", alpha = 0.4, colour = "black") +
  geom_vline(xintercept = slope_real, size = 1, 
             linetype = "dashed", colour = "black") + 
  theme_classic()



abs_simulated_slopes <- abs(simulated_slopes)
exceed_count <- length(abs_simulated_slopes[abs_simulated_slopes >= 
                                              abs(slope_real)])
p_val <- exceed_count / nreps
p_val

##### ANOVA ####
anova(lm(genus_size~gestation_mo*life_mo*litter_size, data=mammals_g))

##### Linear Regression #####
regression <- lm(genus_size~litter_size, data=mammals_g)
ggplot(mammals_g, aes(x = litter_size, y = genus_size)) +
  geom_point() +
  geom_smooth(method = "lm")

summary(regression)

##### Diagnostic Plots for Model Assumptions #####
#Litter Size
plot(result_litter)

#Newborn Mass
plot (result_newborn)
