---
title: "Untitled"
output: html_document
---

```{r}
mammals_c <- read.csv('mammals_clean.csv')
mammals_g <- read.csv('mammals_genus.csv')
mammals_o <- read.csv('mammals_order.csv')

library(tidyverse)
```

```{r}
qplot(data = mammals, x = newborn.g., y = max..life.mo.)
```
```{r}
qplot(data = mammals, x = litter.size, y = max..life.mo.) + coord_cartesian(xlim = c(0,50), ylim = c(0,1000))
```

```{r}
qplot(data = mammals, x = litter.size, y = max..life.mo.) + coord_cartesian(xlim = c(0,50), ylim = c(0,1000))
```

```{r}
colnames(mammals)[colnames(mammals)=="litters.year"] <- "litters_per_year"

mammals <- mammals %>% 
  mutate(litters_per_year = ifelse(litters_per_year == -999.00, NA, litters_per_year))
```

```{r}
write.csv(mammals, "mammals_clean.csv")
```

```{r}
mammals %>%
  group_by(order) %>% 
  tally()
```
```{r}
mammals <- head(mammals, 1440)
```


```{r}
mammals2 <- mammals %>%
  group_by(order) %>% 
  summarize(order_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))
```

```{r}
qplot(data = mammals2, x = order_size, y = gestation_mo)
```

```{r}
qplot(data = mammals2, x = order_size, y = newborn_g)
```

```{r}
qplot(data = mammals2, x = order_size, y = weaning_mo)
```

```{r}
qplot(data = mammals2, x = order_size, y = mass_g)
```

```{r}
qplot(data = mammals2, x = order_size, y = litter_size)
```

```{r}
qplot(data = mammals2, x = order_size, y = litters_per_year)
```

```{r}
mammals3 <- mammals %>%
  group_by(Genus) %>% 
  summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))
```

```{r}
qplot(data = mammals_g, y = genus_size, x = gestation_mo)
```

```{r}
result <- lm(genus_size~gestation_mo, data=mammals3)
summary(result)
```

```{r}
write.csv(mammals2, "mammals_order.csv")
write.csv(mammals3, "mammals_genus.csv")
```

#statistical analysis for gestation mass

```{r}
result <- lm(genus_size~gestation_mo, data=mammals_g)
summary(result)
```
#randomization test
```{r}
set.seed(16)
reshuffled <- mammals_c
reshuffled$gestation_mo <- sample(reshuffled$gestation_mo, size = nrow(reshuffled), replace = FALSE)

slope_real <- coef(result)["gestation_mo"]

simulated_slopes <- list()

nreps = 5000 # 5000 iterations

for(i in 1:nreps){
    
    reshuffled <- mammals_c
    reshuffled$gestation_mo <- sample(reshuffled$gestation_mo, size = nrow(reshuffled),
                                      replace = FALSE)
    
    # Calculate the slope
    genus_temp <- reshuffled %>%
          group_by(Genus) %>% 
          summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
                    gestation_mo = mean(gestation_mo, na.rm = TRUE),
                    newborn_g = mean(newborn_g, na.rm = TRUE),
                    weaning_mo = mean(weaning_mo, na.rm = TRUE),
                    wean_g = mean(wean_g, na.rm = TRUE),
                    afr_mo = mean(afr_mo, na.rm = TRUE),
                    life_mo = mean(life_mo, na.rm = TRUE),
                    litter_size = mean(litter_size, na.rm = TRUE),
                    litters_per_year = mean(litters_per_year, na.rm = TRUE))
    
    reshuffled_res <- lm(genus_size~gestation_mo, data=genus_temp)
    slope_sim <- coef(reshuffled_res)["gestation_mo"]
    
    # Append simulated slope to list
    simulated_slopes[i] <- slope_sim
}    

# Unlist simulated means list into numeric vector
simulated_slopes <- unlist(simulated_slopes)

ggplot() +
    ylab("Count") + xlab("Simulated Slope") +
    geom_histogram(aes(x = simulated_slopes), bins = 30, 
                   fill = "grey", alpha = 0.4, colour = "black") +
    geom_vline(xintercept = slope_real, size = 1, 
               linetype = "dashed", colour = "black") + 
    theme_classic()
```


```{r}
abs_simulated_slopes <- abs(simulated_slopes)
exceed_count <- length(abs_simulated_slopes[abs_simulated_slopes >= 
                                               abs(slope_real)])
p_val <- exceed_count / nreps
p_val
```

#anova
```{r}
anova(lm(genus_size~mass_g+newborn_g+wean_g+afr_mo+litters_per_year+gestation_mo+life_mo+litter_size+weaning_mo+life_mo, data=mammals_g))
```
```{r}
anova(lm(genus_size~gestation_mo*life_mo*litter_size*weaning_mo*life_mo, data=mammals_g))
```



#linear regression
```{r}
regression <- lm(genus_size~gestation_mo, data=mammals_g)
ggplot(mammals_g, aes(x = gestation_mo, y = genus_size)) +
    geom_point() +
    geom_smooth(method = "lm") + ylab('genus size') + xlab('months of gestation')
```
#without rodents
```{r}
mammals_c %>%
  filter(order != "Rodentia") %>% 
  group_by(Genus) %>% 
  summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE)) %>% 
  ggplot(aes(x = gestation_mo, y = genus_size)) +
    geom_point() +
    geom_smooth(method = "lm")
  
```

```{r}
genus_no_rod <- mammals_c %>%
  filter(order != "Rodentia") %>% 
  group_by(Genus) %>% 
  summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))
regression2 <- lm(genus_size~gestation_mo, data=genus_no_rod)
summary(regression2)
```

#drop one
```{r}
genus_no_cet <- mammals_c %>%
  filter(order != "Cetacia") %>% 
  group_by(Genus) %>% 
  summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))
regression3 <- lm(genus_size~gestation_mo, data=genus_no_cet)
summary(regression3)
```

```{r}
genus_no_per <- mammals_c %>%
  filter(order != "Perissodactyla") %>% 
  group_by(Genus) %>% 
  summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))


anova(lm(genus_size~gestation_mo*litter_size, data=genus_no_per))
```



```{r}
genus_no_prim <- mammals_c %>%
  filter(order != "Primate") %>% 
  group_by(Genus) %>% 
  summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
            gestation_mo = mean(gestation_mo, na.rm = TRUE),
            newborn_g = mean(newborn_g, na.rm = TRUE),
            weaning_mo = mean(weaning_mo, na.rm = TRUE),
            wean_g = mean(wean_g, na.rm = TRUE),
            afr_mo = mean(afr_mo, na.rm = TRUE),
            life_mo = mean(life_mo, na.rm = TRUE),
            litter_size = mean(litter_size, na.rm = TRUE),
            litters_per_year = mean(litters_per_year, na.rm = TRUE))
regression5 <- lm(genus_size~gestation_mo, data=genus_no_prim)
summary(regression5)
```






```{r}
result <- lm(genus_size~litter_size, data=mammals_g)
summary(result)
```

```{r}
set.seed(16)
reshuffled <- mammals_c
reshuffled$litter_size <- sample(reshuffled$litter_size, size = nrow(reshuffled), replace = FALSE)
slope_real <- coef(result)["litter_size"]
simulated_slopes <- list()
nreps = 5000
for(i in 1:nreps){
  
  reshuffled <- mammals_c
  reshuffled$litter_size <- sample(reshuffled$litter_size, size = nrow(reshuffled),
                                    replace = FALSE)
  
  # Calculate the slope
  genus_temp <- reshuffled %>%
    group_by(Genus) %>% 
    summarize(genus_size = n_distinct(species), mass_g = mean(mass_g, na.rm = TRUE),
              gestation_mo = mean(gestation_mo, na.rm = TRUE),
              newborn_g = mean(newborn_g, na.rm = TRUE),
              weaning_mo = mean(weaning_mo, na.rm = TRUE),
              wean_g = mean(wean_g, na.rm = TRUE),
              afr_mo = mean(afr_mo, na.rm = TRUE),
              life_mo = mean(life_mo, na.rm = TRUE),
              litter_size = mean(litter_size, na.rm = TRUE),
              litters_per_year = mean(litters_per_year, na.rm = TRUE))
  
  reshuffled_res <- lm(genus_size~litter_size, data=genus_temp)
  slope_sim <- coef(reshuffled_res)["litter_size"]
  
  # Append simulated slope to list
  simulated_slopes[i] <- slope_sim
}    




simulated_slopes <- unlist(simulated_slopes)
ggplot() +
    ylab("Count") + xlab("Simulated Slope") +
    geom_histogram(aes(x = simulated_slopes), bins = 30, 
                   fill = "grey", alpha = 0.4, colour = "black") +
    geom_vline(xintercept = slope_real, size = 1, 
               linetype = "dashed", colour = "black") + 
    theme_classic()


abs_simulated_slopes <- abs(simulated_slopes)
exceed_count <- length(abs_simulated_slopes[abs_simulated_slopes >= 
                                              abs(slope_real)])
p_val <- exceed_count / nreps
p_val
```






